### ISSUE TITLE
Transfer project to sugarlabs

### ISSUE THREAD

**Issue by davelab6** [sugarlabs/maps-activity#1]
Please check out https://wiki.sugarlabs.org/go/Infrastructure_Team/Migrating_to_GitHub and transfer this repo to https://github.com/sugarlabs :)

**Comment by cvgarciarea** [comment]
I tried it, but github was throw:
You don’t have admin rights to sugarlabs

**Comment by davelab6** [comment]
I sent you an invite :)

**Comment by cvgarciarea** [comment]
It's done

**Comment by davelab6** [comment]
👯 

Thanks!

**Comment by davelab6** [comment]
@cristian99garcia actually there are a bunch of sugar activities.... would you be willing to transfer them all? :) https://github.com/search?q=user%3Acristian99garcia+sugar
